FROM python:3.8-bullseye

RUN python --version

RUN apt-get update \
    && apt-get install -y build-essential wget \
        libgl1-mesa-dev libgl1-mesa-glx libglew-dev libosmesa6-dev \
        software-properties-common patchelf libopenmpi-dev \
    && rm -rf /var/lib/apt/lists/*

RUN cd /root \
    && mkdir .mujoco \
    && wget -q https://mujoco.org/download/mujoco210-linux-x86_64.tar.gz \
    && tar -xf mujoco210-linux-x86_64.tar.gz -C .mujoco \
    && rm mujoco210-linux-x86_64.tar.gz

RUN pip install --no-cache-dir onnxruntime free-mujoco-py

RUN pip install --no-cache-dir "typing-extensions>=3.6.6,<4.6.0" \
    && pip install --no-cache-dir \
        torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 \
        --extra-index-url https://download.pytorch.org/whl/cu113 \
    && pip install --no-cache-dir tensorflow==2.13.1 \
    && pip install --no-cache-dir "wandb==0.15.12" "moviepy==1.0.3" "opencv-python<4.10" \
    && pip install --no-cache-dir "typing-extensions>=3.6.6,<4.6.0"

RUN pip install --no-cache-dir mpi4py setuptools==65.5.0 "wheel<0.40.0" \
    && pip install --no-cache-dir gym\<0.26 gymnasium==0.29.1 \
    && pip install --no-cache-dir pandas==1.5.3 matplotlib==3.6.2 \
    && pip install --no-cache-dir stable_baselines3==2.3.0 --no-deps \
    && pip install --no-cache-dir numpy==1.23.4 imageio-ffmpeg==0.4.9 scikit-learn==1.3.2 \
    && pip install --no-cache-dir comet_ml

RUN echo "git config --global --add safe.directory /usr/home/workspace" >> ~/.bashrc

ENV LD_LIBRARY_PATH="/root/.mujoco/mujoco210/bin:${LD_LIBRARY_PATH}"
WORKDIR /usr/home/workspace
